"""add index on episodes.air_date

Revision ID: f437cd782b1b
Revises: 0001_initial
Create Date: 2026-07-08 23:29:41.986234+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f437cd782b1b"
down_revision: str | Sequence[str] | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Pruned by hand from the autogenerated diff — --autogenerate also picked
    up several unrelated pre-existing drift issues between the ORM models
    and the live schema (a constraint-vs-index representation quirk on
    background_tasks/rss_feeds, and hand-written indexes not mirrored in the
    model declarations: ix_episodes_show_id_file_tracked,
    ix_rss_subscriptions_unique_stub_per_show, ix_shows_aliases_gin). None of
    those are part of this change; dropping ix_shows_aliases_gin in
    particular would break the GIN-indexed alias lookup the matching
    pipeline depends on. Only the intended new index is applied here.
    """
    op.create_index(op.f("ix_episodes_air_date"), "episodes", ["air_date"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_episodes_air_date"), table_name="episodes")
