// This file is hand-maintained, not auto-generated. Most types below are
// thin aliases (or Omit<>+override narrowings) over the real backend
// schemas in `./api-generated.ts`, which IS auto-generated by
// `make.py generate-types` and safe to regenerate at any time.
//
// A type here needs an override (rather than a plain alias) when the
// backend schema is looser than what the frontend actually relies on —
// most commonly a bare `string` where the frontend narrows to a literal
// union (e.g. TaskStatus), or a generic dict where the frontend narrows to
// a known shape (e.g. TmdbGenre[] instead of Record<string, unknown>[]).
// It stays a fully hand-written interface (no `components["schemas"]`
// reference at all) when there is no corresponding backend schema — TMDB
// proxy endpoints return raw `dict[str, Any]`, WebSocket payloads aren't
// part of the REST OpenAPI spec, and a few types are frontend-only
// compositions with no single backing endpoint.
//
// After running `make.py generate-types`, diff `api-generated.ts` against
// this file's `Omit<>` overrides — a schema rename or a newly-loosened
// field will show up as a type error here, not a silent drift.

import type { components } from './api-generated'

// ─── Shows ────────────────────────────────────────────────────────────────

export interface TmdbGenre {
  id: number
  name: string
}

export interface TmdbNetwork {
  id: number
  name: string
  logo_path: string | null
  origin_country: string
}

export type ShowList = Omit<components['schemas']['ShowList'], 'genres' | 'networks'> & {
  genres: TmdbGenre[] | null
  networks: TmdbNetwork[] | null
}

export type ShowRead = Omit<
  components['schemas']['ShowRead'],
  'genres' | 'networks' | 'aliases_sources'
> & {
  genres: TmdbGenre[] | null
  networks: TmdbNetwork[] | null
  aliases_sources: { tmdb: string[]; llm: string[]; user: string[] } | null
}

export type ShowCreate = Omit<
  components['schemas']['ShowCreate'],
  'vote_count' | 'genres' | 'networks'
> & {
  vote_count?: number
  genres?: TmdbGenre[] | null
  networks?: TmdbNetwork[] | null
}

export type ShowPaths = components['schemas']['ShowPaths']

export type ShowPatch = components['schemas']['ShowPatch']

// ─── Episodes ─────────────────────────────────────────────────────────────

export type BackingFile = components['schemas']['BackingFile']

export type EpisodeList = Omit<components['schemas']['EpisodeList'], 'tracked_source'> & {
  tracked_source: 'match' | 'import' | null
}

export interface EpisodeRead extends EpisodeList {
  tmdb_id: number
  overview: string | null
  runtime: number | null
  still_path: string | null
  created_at: string
  updated_at: string
}

// ─── Files ────────────────────────────────────────────────────────────────

export type ShowBrief = components['schemas']['jidou__schemas__file_schema__ShowBrief']

export type EpisodeBrief = components['schemas']['EpisodeBrief']

export type FileStatus = components['schemas']['FileStatus']

export interface FileList {
  id: number
  original_filename: string
  remote_path: string
  file_size: number
  status: FileStatus
  show_id: number | null
  episode_id: number | null
  parsed_show_name: string | null
  created_at: string
}

// show_id/episode_id/show/episode are forced non-optional here: the
// backend fields are Optional-with-default, which pydantic always
// serializes (never omits the key), but openapi-typescript still marks
// them `?` — see the file header comment.
export type FileRead = Omit<
  components['schemas']['FileRead'],
  'show_id' | 'episode_id' | 'show' | 'episode'
> & {
  show_id: number | null
  episode_id: number | null
  show: ShowBrief | null
  episode: EpisodeBrief | null
}

export type ContentType = 'tv' | 'anime' | 'movie'

export type FileMatchRequest = Omit<
  components['schemas']['FileMatchRequest'],
  'tmdb_media_type' | 'content_type'
> & {
  tmdb_media_type?: 'tv' | 'movie' | null
  content_type?: ContentType | null
}

export interface TmdbSuggestion {
  tmdb_id: number
  title: string | null
  media_type: string | null
  overview: string | null
  poster_path: string | null
  first_air_date: string | null
  vote_average: number | null
}

export interface TmdbSuggestionsResponse {
  query: string
  results: TmdbSuggestion[]
}

// ─── Tasks ────────────────────────────────────────────────────────────────

export type TaskStatus = components['schemas']['TaskStatus']

// No standalone backend schema exists for this — task_type is a Literal[...]
// (not an Enum class), so FastAPI inlines it per-field instead of hoisting
// it to its own components.schemas entry. Derive it from a field that has it.
export type TaskType = components['schemas']['TaskList']['task_type']

export type TaskList = components['schemas']['TaskList']

export type TaskRead = Omit<components['schemas']['TaskRead'], 'event_log'> & {
  event_log: TaskEvent[]
}

export type TaskTrigger = Omit<components['schemas']['TaskTrigger'], 'task_type' | 'dry_run'> & {
  task_type: TaskType
  dry_run?: boolean
}

// ─── WebSocket messages ───────────────────────────────────────────────────
// Not part of the REST OpenAPI spec — these describe WebSocket frame
// payloads, so there is no backend schema to alias.

export type WsMessageType = 'progress' | 'file_update' | 'complete' | 'error' | 'cancelled' | 'event'

export interface TaskEvent {
  ts: string
  level: 'info' | 'warn' | 'error'
  msg: string
  ctx?: Record<string, unknown>
}

export interface WsProgressData {
  current: number
  total: number
  message: string
}

export interface WsFileUpdateData {
  filename: string
  action: string
}

export interface WsCompleteData {
  summary: Record<string, unknown>
}

export interface WsErrorData {
  error: string
}

export type WsMessage =
  | { type: 'progress'; data: WsProgressData }
  | { type: 'file_update'; data: WsFileUpdateData }
  | { type: 'complete'; data: WsCompleteData }
  | { type: 'error'; data: WsErrorData }
  | { type: 'cancelled'; data: Record<string, never> }
  | { type: 'event'; data: TaskEvent }

// ─── Config ───────────────────────────────────────────────────────────────
// GET /config and the connection-test endpoints return raw dict[str, Any]
// (no response_model) — hand-written, no backend schema to alias.

export interface MediaPathEntry {
  container: string
  host: string
}

export interface MediaPaths {
  tv: MediaPathEntry
  anime: MediaPathEntry
  movie: MediaPathEntry
}

export interface AppConfig {
  app_name: string
  debug: boolean
  database_url: string | null
  redis_url: string | null
  tmdb_api_key_set: boolean
  tmdb_base_url: string
  sftp_host: string | null
  sftp_port: number
  sftp_username: string | null
  llm_provider: string
  llm_model: string
  llm_base_url: string | null
  media_paths: MediaPaths
  rss_config_path_set: boolean
  api_key_enabled: boolean
  sync_schedule_enabled: boolean
  sync_schedule_hours: string
  rss_import_schedule_enabled: boolean
  rss_import_schedule_hours: string
}

// ─── Runtime settings ──────────────────────────────────────────────────────────

export type AppSettings = components['schemas']['AppSettingsRead']

export type AppSettingsPatch = components['schemas']['AppSettingsPatch']

// ─── Dashboard ─────────────────────────────────────────────────────────────────

export interface RecentShowItem {
  id: number
  tmdb_id: number
  title: string
  media_type: string
  content_type: string | null
  poster_path: string | null
  backdrop_path: string | null
  overview: string | null
  tagline: string | null
  vote_average: number | null
  genres: TmdbGenre[] | null
  release_date: string | null
  status: string | null
  number_of_seasons: number | null
  number_of_episodes: number | null
  runtime: number | null
  created_at: string
  adult: boolean | null
}

export type DashboardShowSummary = Omit<
  components['schemas']['DashboardShowSummary'],
  'genres'
> & {
  genres: TmdbGenre[] | null
}

export type RecentEpisodeItem = Omit<components['schemas']['RecentEpisodeItem'], 'show'> & {
  show: DashboardShowSummary
}

// ─── RSS ──────────────────────────────────────────────────────────────────────

export type RssFeedRead = components['schemas']['RssFeedRead']

export type RssFeedCreate = Omit<components['schemas']['RssFeedCreate'], 'active'> & {
  active?: boolean
}

export type RssFeedUpdate = components['schemas']['RssFeedUpdate']

export type RssShowBrief = components['schemas']['RssShowBrief']

export type RssSubscriptionRead = components['schemas']['RssSubscriptionRead']

export type RssSubscriptionCreate = Omit<
  components['schemas']['RssSubscriptionCreate'],
  'regex_include_ignorecase' | 'regex_exclude_ignorecase' | 'active' | 'enabled_in_config'
> & {
  regex_include_ignorecase?: boolean
  regex_exclude_ignorecase?: boolean
  active?: boolean
  enabled_in_config?: boolean
}

export type RssSubscriptionUpdate = components['schemas']['RssSubscriptionUpdate']

export type RssRegexSuggestion = components['schemas']['RssRegexSuggestion']

export type RssSubscriptionRecommendation = components['schemas']['RssSubscriptionRecommendation']

export type RssSubscriptionBulkPatchItem = components['schemas']['RssSubscriptionBulkPatchItem']

export interface ConnectionTestResult {
  ok: boolean
  error?: string
  message?: string
}

// ─── Admin ────────────────────────────────────────────────────────────────

export type AdminStats = components['schemas']['StatsResponse']

export interface FileTimelineEntry {
  date: string
  count: number
}

export interface PipelineStatusEntry {
  status: string
  count: number
}

export interface ServiceHealth {
  ok: boolean
  configured?: boolean
  latency_ms?: number
  error?: string
  provider?: string
  model?: string
}

export interface HealthCheck {
  healthy: boolean
  services: {
    database: ServiceHealth
    redis: ServiceHealth
    tmdb: ServiceHealth
    llm: ServiceHealth
  }
}

export interface CacheEntry {
  label: string
  key: string
}

export interface CacheStats {
  count: number
  maxsize: number
  ttl_seconds: number
  entries: CacheEntry[]
}

// ─── Watchlist ────────────────────────────────────────────────────────────

export type WatchlistStatus = components['schemas']['WatchlistStatus']

export type WatchlistShowBrief = components['schemas']['jidou__schemas__watchlist_schema__ShowBrief']

// Frontend-only slice type — no endpoint returns a bare WatchlistList, but
// it's still exercised directly in tests, so it stays hand-written rather
// than derived from WatchlistRead.
export interface WatchlistList {
  id: number
  show_id: number
  show: WatchlistShowBrief
  status: WatchlistStatus
  position: number
  created_at: string
}

export type WatchlistRead = Omit<components['schemas']['WatchlistRead'], 'notes'> & {
  notes: string | null
}

export type WatchlistCreate = Omit<
  components['schemas']['WatchlistCreate'],
  'status' | 'position'
> & {
  status?: WatchlistStatus
  position?: number
}

export type WatchlistUpdate = components['schemas']['WatchlistUpdate']

export type WatchlistPositionItem = components['schemas']['WatchlistPositionItem']

// ─── Orphaned Tracking Records ────────────────────────────────────────────

export type OrphanedTrackingRecord = Omit<
  components['schemas']['OrphanRead'],
  'tracked_source'
> & {
  tracked_source: 'match' | 'import'
}

// ─── File PATCH ───────────────────────────────────────────────────────────

export type FilePatch = components['schemas']['FilePatch']

// ─── Show local-directory scan ─────────────────────────────────────────────

export type ScannedFileMatch = components['schemas']['ScannedFileMatch']

// ─── TMDB raw responses (proxied through backend) ─────────────────────────
// TMDB search/trending/details endpoints return raw dict[str, Any] — no
// response_model, so no backend schema to alias.

export interface TmdbResult {
  id: number
  title?: string
  name?: string
  overview: string
  poster_path: string | null
  backdrop_path: string | null
  vote_average: number
  vote_count: number
  release_date?: string
  first_air_date?: string
  media_type?: string
  original_language: string
  genre_ids?: number[] | null
  origin_country?: string[] | null
  adult?: boolean | null
}

export interface TmdbSearchResponse {
  results: TmdbResult[]
  total_results: number
  total_pages: number
  page: number
}

// GET /shows/discover returns a synthesized feed (recommendations merged with
// trending), not a single raw TMDB response, but the field shape still
// mirrors TmdbResult's (so it can feed directly into the existing
// add-to-library flow). media_type is narrowed from the backend's bare
// string, and seeded_from is forced non-optional — the backend field always
// has a value (empty list default), but openapi-typescript still marks a
// field with a default as `?` — see the FileRead comment above for the same
// pattern.
export type DiscoverResult = Omit<
  components['schemas']['DiscoverResult'],
  'media_type' | 'seeded_from'
> & {
  media_type: 'tv' | 'movie'
  seeded_from: string[]
}

// ─── Path Import ──────────────────────────────────────────────────────────────
// Celery task result payloads, not a live HTTP response_model — no backend
// schema to alias.

export interface ShowImportResult {
  show_dir: string
  tmdb_id: number | null
  tmdb_title: string | null
  action: 'created' | 'found' | 'not_found'
  episodes_tracked: number
  episodes_unmatched: number
}

export interface PathImportResult {
  shows_processed: number
  shows_created: number
  shows_found: number
  shows_not_found: number
  episodes_tracked: number
  episodes_unmatched: number
  show_results: ShowImportResult[]
}

// ─── Calendar ─────────────────────────────────────────────────────────────

export type CalendarEpisode = components['schemas']['CalendarEpisode']
